### ISSUE TITLE
error  in  create react app 

### ISSUE THREAD

**Issue by ifnk** [KondakovArtem/react-hexviewer-ts#2]
i use create react app -typescript ,and yarn add react-hexviewer-ts 
my byteArr is AAL/AAAAAAAAAAAAAA== 
i also convert to hex 0002ff00000000000000000000

then i use your components 
            <HexViewer>{byteArrHex}</HexViewer>
or   <HexViewer>{byteArr}</HexViewer>

their all not work ,and console has error 

![image](https://user-images.githubusercontent.com/39295458/221355855-12ad88ea-bec1-417b-bb73-507a24d2bdae.png)

how can i fix it ?

**Comment by KondakovArtem** [comment]
Hi, can you prepare an example of reproducing an error in stackblitz and share a link to it, I'll look at it, correct it or tell you what the problem is

**Comment by ifnk** [comment]
> Hi, can you prepare an example of reproducing an error in stackblitz and share a link to it, I'll look at it, correct it or tell you what the problem is

hey ,this is my  example  https://stackblitz.com/edit/react-ts-ve93km?file=package.json

**Comment by KondakovArtem** [comment]
Hi, I think I solved the problem in version ^0.2.3. The component used its own version of react. Now it's gone. Also, do not forget to include styling, otherwise the layout of the component will not work

**Comment by ifnk** [comment]
> Hi, I think I solved the problem in version ^0.2.3. The component used its own version of react. Now it's gone. Also, do not forget to include styling, otherwise the layout of the component will not work

oh ,is run without error ! but i used css style ,i read doc  only support less and scss , how can i  import css style to display normal ?

**Comment by ifnk** [comment]
> Hi, I think I solved the problem in version ^0.2.3. The component used its own version of react. Now it's gone. Also, do not forget to include styling, otherwise the layout of the component will not work

and i only run command  `npm i react-hexviewer-ts  `   to install package ,but the  version is `    "react-hexviewer-ts": "^0.1.8",
`  in my package.json  , so i not notice react-hexviewer-ts version
